# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-01-09 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('author', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField()),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('time_published', models.DateTimeField()),
                ('guid', models.CharField(max_length=255)),
                ('guid_is_uri', models.BooleanField()),
                ('uri_src', models.URLField()),
                ('file_type', models.CharField(max_length=25)),
                ('hash_sha1', models.CharField(default='', max_length=40)),
                ('state', models.CharField(choices=[('QD', 'queued'), ('OK', 'ok'), ('WR', 'warn'), ('ER', 'error')], default='QD', max_length=2)),
                ('file', models.FileField(null=True, upload_to='')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Channel')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set([('channel', 'guid')]),
        ),
    ]
