# noqa
# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-01-09 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):  # noqa

    dependencies = [
        ('data', '0002_auto_20200109_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='data.Channel'),
        ),
    ]
